version: "3"

services:
  nextjs:
    container_name: portfolio-site
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "127.0.0.1:3000:3000"
    # Tambahkan environment variables jika diperlukan
    # environment:
    #   - DATABASE_URL=your_database_url
